name: solicitud_toner
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-266.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: null
  hive_flutter: null
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.5
  window_manager: ^0.3.1

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
